sudo: required
language: python
python:
  - '3.4'
  - '3.5'
  - '3.6'
env:
  global:
    - secure: MKsfJ8DYCRx7I9bX84ww53Nf/0tgdNYDL1zT17itGfxz9C23rJbiiRrpRyKLCibn+c6ognfighxgnhBTis58m5a/8/06fC/rIM4yVBrok/m/8DNnH5p35QoH3V23TC08nWkwCZfh42DzOX0+63ODK0pvrD2bjDM4cs6+uVnCr3SBEwkOiE087SHGOZAkf4KV9hqm1qqJj0WYWgw1hVYWzfWPLI6jr9kLh1hJ2puMAs6/cry9AuhwyEb3ti+Rng6sIb7Rm86JTaVDNRJlN1Y4IWoINmVP1HhwKOuBVszCUCJwqWfupXrMkeJN2TIsZhM9f27WjjONAGDj3C08pO36qH8pOwTVPjs4Z+loFf5HpIjO+yfYzJ98TENrP39ipwWlVv9L7x0qMP3cLnSIn/TVIM/AXC2dTR3SotU76bX9wNGkdrKfAoeSVc0IJgLrLBtXy244lY9KbO9qvu5f4xyRHrMYVsYZkV+FJ1TQtPDrGu05yiu1Tx5zMb6MGh0YlOYh4YTWOdElXOHw6A0Il+pCLFeEeWh435GHNHpNevudtZ/f4gmtYt65gx2VRhGm2jgefRU+h/Mb2SAB77zIdMXDRTZjMawWqL4enkzJRhF3WT75D0zdNjCrdExMe9muCKbnbpdZHoRniS19u3A++FZt2/j/PkhbYQUuaFEVfSTCDWM=
install: pip install tox-travis
script: tox --travis-after
notifications:
  email:
    recipients:
      - service@soocii.me
deploy:
  provider: pypi
  user: SoociiDev
  password:
    secure: V2Al/N2LbZk5CLn+sfb7Q2dqDiW/vHInSYWrYLGHiPg24+WtXI2hXFgAE6kFIqUfvLFbK89pC/N8ZrI+w9v9pThwcO42mibmcHrspGToJj8f+65hTj0urYHuiwrheh6M8VA5osL71Pz3FLkqWUQCqCMq0OS35m08AYF68idxWkdXTUgORZ5dj5q50MtM3f3ngcC/AxeBhNFIxq2CW7Vl+rkVew3yorOQmTBhPy6PDXw1NuXf/YCC1M3Qk7ii8ei4MPlG6mg2D7tVzstGdIA+4Dy/OcSDxTlAjSnyrNas5lSQvPkL2bPu76OfaNs973JzLvn4gydnEgTU3Ss7VPwjkmI2QM9yMlV7dOQP68YkliGmmnNL82XyBlBQeWFf5zK7z53GBKtQxXWwlhFS3v8cPPUmdZOBGoRwaayqHaBmkCixU65eSGxM1SS/Qk/GpjVBu3t7M++jjAIpOf8fhFkfJYYcsNcRFKphkSAeUPu9toIo4/kGdHRDAPr41PfkZe6H3g7ls5pSCxloQ9eBGhqHHCI0V36dG7W2EUv7xQuSFZpC9PBp7Vh8PmdsAXhmCoGY3E1Rzhsn55bmVlcYj01NB4hPc53y3N3JNX8b8D9KM47Gxfk31qM5SAg9HDO+SjnqNd6Uhy9Dwz6GdZ8KZtOQC/wYTfd0jLMGnS9BlVQmZss=
  on:
    branch: master
    tags: true
    python: 3.5
